:toc:

== 3 - Relay board sketch

After breadboard prototype done at link:2-relay-board-prototype.adoc[02 Relay Board Prototype]

Now is time for a bit of coding.

=== How-To

Here is the first link:sketches/esp8266-web-relay-wifi/esp8266-web-relay-wifi.ino[Basic sketch]

Details of mathematics in next section.

Steps:

- Uploaded from Arduino IDE
- Open Arduino console
- This should log the URL with IP address to connect to Wifi device
- Connect using browser to see the table where you can switch on and off the relays

=== Mathematics

==== Binary computation

We have wired 16 outputs.

The outputs can be mapped to an integer from 0 to 65535.

In Arduino code, this means link:https://www.arduino.cc/en/Reference/UnsignedInt[__unsigned int__]

Let's see what this means from link:http://playground.arduino.cc/Code/BitMath#quickref[Byte mathematics]

```js
unsigned int relayState = 0;

// state of each relay (switchId is relay number from 0 to 15):
boolean switchState = ((relayState >> switchId) & 1);

// Set relay to 0:
relayState &= ~(1 << relayNb);

// Set relat to 1:
relayState |= (1 << relayNb);
```

==== 74HC595 - ShiftOut

The link:https://www.arduino.cc/en/Reference/ShiftOut[74HC595 ShiftOut] states that it is 8 bit and requires two steps operation to shift bits.

```js
// Value is anything between 0 to 65535 representing 16 bits of data I/Os
void switchRelay(int value) 
{
   // take the latchPin low:
   digitalWrite(latchPin, LOW);

   // shift out the highbyte
   shiftOut(dataPin, clockPin, MSBFIRST, (value >> 8));
   // shift out the lowbyte
   shiftOut(dataPin, clockPin, MSBFIRST, value);

   //take the latch pin high so the LEDs will light up:
   digitalWrite(latchPin, HIGH);
}
```
